### ISSUE TITLE
Microsoft signalr package is now at version 8(.0.7)

### ISSUE THREAD

**Issue by bzuidgeest** [dreamonkey/vue-signalr#4]
I tried installing your package tonight and I got some errors.

I think this is the relevant part (i'm mostly into backend stuff):
npm error Found: @microsoft/signalr@8.0.7
npm error node_modules/@microsoft/signalr
npm error   @microsoft/signalr@"^8.0.7" from the root project
npm error
npm error Could not resolve dependency:
npm error peer @microsoft/signalr@"^5.0.0 || ^6.0.0 || ^7.0.0" from @dreamonkey/vue-signalr@1.1.0

I seem to have version 8.0.7 version of the microsoft signalr package while yours only deals with up to version 7. 

Is it possible for you to update the dependencies?

**Comment by IlCallo** [comment]
Seems like there hasn't been any major changes with SignalR 8, so I bumped all deps and tagged a new release
Let me know if you hit any issue with it
